name: Spring Boot CI

on:
  push:
    branches:
      - main

jobs:

  build-user:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build User Service
        run: mvn clean install -DskipTests

  build-product:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Product

    steps:

      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Product Service
        run: mvn clean install -DskipTests
